---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine

inputs:
  - name: metadata
  - name: service-repo

outputs:
  - name: build-output
  - name: keyvalout

params:
  GROUP:

run:
  path: service-repo/ci/tasks/meta-data/task.sh
