---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: askxtreme/java8-node
    tag: base
inputs:
  - name: keyval
  - name: service-repo
outputs:
  - name: build-output
  - name: keyvalout
params:
  TERM: -dumb
  GRADLE_OPTS: -Dorg.gradle.native=false
run:
  path: service-repo/ci/tasks/build-service/task.sh

#run:
#  path: "service-repo/gradlew"
#  args: ["--build-file", "source-code/build.gradle", "build"]
