---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: askxtreme/java8-node
    tag: base
inputs:
  - name: keyval
  - name: service-repo
outputs:
  - name: test-output
  - name: keyvalout
params:
  JFROG_SERVER:
  JFROG_URL:
  JFROG_USER:
  JFROG_PASSWORD:
  JFROG_LOCATION:
  TARGET_ENV: "development"
run:
  path: service-repo/ci/tasks/smoke-test/task.sh
