resource_types:
- name: meta
  type: docker-image
  source:
    repository: swce/metadata-resource
    tag: latest
    username: ((docker-user))
    password: ((docker-passwd))

- name: keyval
  type: docker-image
  source:
    repository: swce/keyval-resource
    tag: latest
    username: ((docker-user))
    password: ((docker-passwd))

resources:
- name: metadata
  type: meta
- name: keyval
  type: keyval
- name: service-repo
  type: git
  source:
    uri: {{git-url}}
    branch: {{git-branch}}
    # username: ((git-username))
    # password: ((git-passwd))

jobs:
- name: meta-data
  plan:
  - get: metadata
  - get: service-repo
    trigger: true
  - task: gen-meta-data
    file: service-repo/ci/tasks/meta-data/task.yml
    params:
      GROUP: {{group}}
  - put: keyval
    params:
      file: keyvalout/keyval.properties

- name: build
  plan:
  - aggregate:
    - get: service-repo
    - get: keyval
      passed:
      - meta-data
#      trigger: true
    - task: build-archive
      file: service-repo/ci/tasks/build-service/task.yml

#       config:
#         platform: linux
#         image_resource:
#           type: docker-image
#           source:
#             repository: busybox
#         outputs:
#           - name: build_output
#         run:
#           path: sh
#           args:
#             - -exc
#             - |
